### ISSUE TITLE
Unit displaylink.service not found.

### ISSUE THREAD

**Issue by leonnoel** [AdnanHodzic/displaylink-debian#23]
Hi,

I am trying to get a MB168B usb monitor to work with a t410 Thinkpad. I've tried installing and reinstalling, but still wind up with the following error: 

>:~$ systemctl status displaylink.service
● displaylink.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
:~$ systemctl start displaylink.service
Failed to start displaylink.service: Unit displaylink.service not found.
 

The only other odd thing I've noticed (installer worked fine) was when trying to uninstall I get the following error:

``
Removing evdi module 
rmmod: ERROR: Module evdi is in use
``

The uninstall, however, does complete.

EDIT: Did manage to remove the module for a full uninstall and reinstall - same problem

Any ideas? Many thanks!

**Comment by TinkerFu** [comment]
I'm having the same issue.  Running Bunsenlabs Hydrogen ( debian jessie ).

**Comment by cilynx** [comment]
Upstream, the service name has been changed from `displaylink.service` to `dlm.service`.  I've submitted the PR you see above to address this in the Post Install Guide.

With respect to the header dependency, upstream is looking for Kconfig (which Ubuntu kernel header packages contain, but Debian kernel header packages do not) in your module build dir:

`# Required kernel version`
`KVER=$(uname -r)`
`KVER_MIN="3.14"`
`version_lt "$KVER" "$KVER_MIN" && missing_requirement "Kernel version $KVER is too old. At least $KVER_MIN is required"`
`# Linux headers`
`[ ! -f "/lib/modules/$KVER/build/Kconfig" ] && missing_requirement "Linux headers for running kernel, $KVER"`

You'll notice that `/lib/modules/$KVER/build` is actually a symlink to `/usr/src/linux-headers-$KVER`:
`lrwxrwxrwx  1 root root     36 Sep 19 14:09 build -> /usr/src/linux-headers-4.7.0-1-amd64`

It turns out that `Kconfig` itself is never actually used by the displaylink / EVDI build process, so you can get away with just `touch`ing Kconfig in your current header directory and everything should build properly after that.

It would be possible within the script here to modify upstream before it runs to check for one of the header files that it actually needs as opposed to looking for `Kconfig`, but I'll leave it up to @AdnanHodzic if he wants to go that far.

**Comment by AdnanHodzic** [comment]
I just wanted to inform you  that I just pushed bunch of updates, one of them is ["Fixed Debian/Kali Linux install bug (failure to identify kernel headers)"](https://github.com/AdnanHodzic/displaylink-debian/commit/e1225f208e30e2aa1ace75969be6c81e479e14df)

Which adequately fixes problem mentioned here.

**Comment by flipside2000** [comment]
Hi AdnanHodzic, I am however still receiving "Unit dlm.service could not be found". This is on a fresh Kali install. Performing the steps as per cilynx' steps above resolves this however. Just a heads up

**Comment by AdnanHodzic** [comment]
Hi @flipside2000, I just pushed changes which take care of this problem, so no need to do @cilynx steps manually anymore.a

**Comment by gitowiec** [comment]
I have the same issue here on Ubuntu 16.04.2 with Dell 7559 laptop and D3100 Displaylink adapter
